/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javagalileo_GalileoSDK */

#ifndef _Included_javagalileo_GalileoSDK
#define _Included_javagalileo_GalileoSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javagalileo_GalileoSDK
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javagalileo_GalileoSDK_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    CreateInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_javagalileo_GalileoSDK_CreateInstance
  (JNIEnv *, jobject);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    ReleaseInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javagalileo_GalileoSDK_ReleaseInstance
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    Connect
 * Signature: (JLjava/lang/String;ZILjavagalileo/listeners/OnConnectEventListener;Ljavagalileo/listeners/OnDisconnectEventListener;)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_Connect
  (JNIEnv *, jobject, jlong, jstring, jboolean, jint, jobject, jobject);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    GetServersOnline
 * Signature: (J)[Ljavagalileo/models/ServerInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_javagalileo_GalileoSDK_GetServersOnline
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    GetCurrentServer
 * Signature: (J)Ljavagalileo/models/ServerInfo;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_GetCurrentServer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    PublishTest
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_PublishTest
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    GetInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_javagalileo_GalileoSDK_GetInstance
  (JNIEnv *, jclass);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SendCMD
 * Signature: (J[B)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_SendCMD
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StartNav
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StartNav
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StopNav
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StopNav
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SetGoal
 * Signature: (JI)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_SetGoal
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    PauseGoal
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_PauseGoal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    ResumeGoal
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_ResumeGoal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    CancelGoal
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_CancelGoal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    InsertGoal
 * Signature: (JFF)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_InsertGoal
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    ResetGoal
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_ResetGoal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SetSpeed
 * Signature: (JFF)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_SetSpeed
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    Shutdown
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_Shutdown
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SetAngle
 * Signature: (JBB)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_SetAngle
  (JNIEnv *, jobject, jlong, jbyte, jbyte);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StartLoop
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StartLoop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StopLoop
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StopLoop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SetLoopWaitTime
 * Signature: (JB)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_SetLoopWaitTime
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StartMapping
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StartMapping
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StopMapping
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StopMapping
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SaveMap
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_SaveMap
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    UpdateMap
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_UpdateMap
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StartChargeLocal
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StartChargeLocal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StopChargeLocal
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StopChargeLocal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SaveChargeBasePosition
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_SaveChargeBasePosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StartCharge
 * Signature: (JFF)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StartCharge
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    StopCharge
 * Signature: (J)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_StopCharge
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    MoveTo
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_javagalileo_GalileoSDK_MoveTo
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    GetGoalNum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javagalileo_GalileoSDK_GetGoalNum
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    GetCurrentStatus
 * Signature: (J)Ljavagalileo/models/GalileoStatus;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_GetCurrentStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SetCurrentStatusCallback
 * Signature: (JLjavagalileo/listeners/OnStatusUpdateEventListener;)V
 */
JNIEXPORT void JNICALL Java_javagalileo_GalileoSDK_SetCurrentStatusCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    SetGoalReachedCallback
 * Signature: (JLjavagalileo/listeners/OnGoalReachedEventListener;)V
 */
JNIEXPORT void JNICALL Java_javagalileo_GalileoSDK_SetGoalReachedCallback
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    WaitForGoal
 * Signature: (JI)Ljavagalileo/models/ServerInfo/GALILEO_RETURN_CODE;
 */
JNIEXPORT jobject JNICALL Java_javagalileo_GalileoSDK_WaitForGoal
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     javagalileo_GalileoSDK
 * Method:    Dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javagalileo_GalileoSDK_Dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
